name: Run Tests

on:
  - push
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile: [ rails_6.0, rails_6.1, rails_7.0 ]
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: RSpec
      run: bundle exec appraisal ${{ matrix.gemfile }} rspec
