name: Ruby Gem

on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bundle exec rspec
