name: Test

on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6, 2.7]
        gemfile: [rails_5.1_stable, rails_5.2_stable, rails_6.0_stable]
        experimental: [false]
        include:
          - ruby: head
            gemfile: rails_5.1_stable
            experimental: true
          - ruby: head
            gemfile: rails_5.2_stable
            experimental: true
          - ruby: head
            gemfile: rails_6.0_stable
            experimental: true
          - ruby: head
            gemfile: rails_edge
            experimental: true
          - ruby: 2.6
            gemfile: rails_edge
            experimental: true
          - ruby: 2.7
            gemfile: rails_edge
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    env:
      BUNDLE_PATH: ${{ github.workspace }}/vendor/bundle
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ matrix.ruby }}-gems-${{ hashFiles(env.BUNDLE_GEMFILE) }}
        restore-keys: |
           ${{ matrix.ruby }}-gems-
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec